export const DOMAIN = 'https://web.truework.com.vn/api/'
export const GET_TASK_LIST = 'GET_TASK_LIST'
export const ADDPRODUCT = 'ADDPRODUCT'
export const UPDATEPRODUCT = 'UPDATEPRODUCT'
export const DETAILPRODUCT = 'DETAILPRODUCT'

export const ADDUSER = 'ADDUSER'
export const UPDATEUSER = 'UPDATEUSER'
export const DETAILUSER = 'DETAILUSER'
export const LOGIN = 'LOGIN'
export const SIGNUP = 'SIGNUP'
export const COMPLETEPROFILE = 'COMPLETEPROFILE'
export const ISSUCCESS = 'ISSUCCESS'
